language: php
sudo: false
cache:
    directories:
        - $HOME/.composer/cache
matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
    include:
        - php: 7.0
        - php: 7.1
        - php: 7.2
          env: WITH_COVERAGE=true
        - php: nightly
before_script:
    - mkdir -p ./build/logs
    - rm ./composer.lock
script:
    - travis_retry composer install --no-interaction
    - composer style-check
    - if [[ "$WITH_COVERAGE" == "true" ]]; then ./vendor/bin/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml --coverage-text; else vendor/bin/phpunit -c phpunit.xml; fi
    - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/coveralls -v; fi;
